apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-deployment
  labels:
    app: engine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
      - name: engine
        image: patobelardo/rpcpoc-engine:1.3
        env:
        - name: engineconnection__port
          value: "8091"
      - name: engine-controller
        image: patobelardo/rpcpoc-engine-controller:1.3
        env:
        - name: rabbitmq__hostname
          value: "10.0.165.99"
        - name: rabbitmq__user
          value: "user"
        - name: rabbitmq__pass
          value: "NOGJ4yPikc"
        - name: engineconnection__hostname
          value: "localhost"
        - name: engineconnection__port
          value: "8091"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
  labels:
    app: webapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: patobelardo/rpcpoc-webapi:1.3
        env:
        - name: rabbitmq__hostname
          value: "10.0.165.99"
        - name: rabbitmq__user
          value: "user"
        - name: rabbitmq__pass
          value: "NOGJ4yPikc"
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: webapi-service
spec:
  selector:
    app: webapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: webapi-service-public
spec:
  type: LoadBalancer
  selector:
    app: webapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80



